kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: pod-autoscale
  namespace: user1-01
spec:
  behavior:
    scaleDown: 
      policies: 
      - type: Pods 
        value: 1 
        periodSeconds: 10 
      - type: Percent
        value: 10 
        periodSeconds: 10
      selectPolicy: Min 
      stabilizationWindowSeconds: 30 
    scaleUp: 
      policies:
      - type: Pods
        value: 5 
        periodSeconds: 10
      - type: Percent
        value: 12 
        periodSeconds: 10
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  scaleTargetRef:
    kind: Deployment
    name: pod-autoscale
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
