kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: pod-autoscale
  namespace: user1-01
spec:
  scaleTargetRef:
    kind: Deployment
    name: pod-autoscale
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
