---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-2
  labels:
    app: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-2
  template:
    metadata:
      labels:
        app: canary-2
    spec:
      containers:
      - name: canary
        image: quay.io/benny12332/canary:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-index-2
          mountPath: /opt/app-root/src
      volumes:
        - name: nginx-index-2
          configMap:
            name: nginx-index-2
---
apiVersion: v1
kind: Service
metadata:
  name: canary-2
spec:
  selector:
    app: canary-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: canary-2
  namespace: user1-canary
  labels: {}
spec:
  to:
    kind: Service
    name: canary-2
  tls: null
  port:
    targetPort: 8080
