apiVersion: v1
kind: Namespace
metadata:
  name: user1-daemonset
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example-app
  namespace: user1-daemonset
spec:
  selector:
    matchLabels:
      app: daemonset-app
  template:
    metadata:
      labels:
        app: daemonset-app
    spec:
      containers:
        - name: daemonset-app
          image: 'quay.io/benny12332/daemonset-lab:1.0'
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: daemonset-app-service
  namespace: user1-daemonset
spec:
  selector:
    app: daemonset-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: daemonset-app-route
  namespace: user1-daemonset
  labels: {}
spec:
  to:
    kind: Service
    name: daemonset-app-service
  tls: null
  port:
    targetPort: 8080
